services:
  my-service:
    image: kur0bot  # Replace with your Docker image name
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
  map-files:
    image: kur0shite/kur0bot  # Replace with your Docker image name
    volumes:
      - ./modules:/app/modules
      - ./myfunctions:/app/myfunctions
      - ./pyproject.toml:/app/pyproject.toml
      - ./main.py:/app/main.py
      - ./keep_alive.py:/app/keep_alive.py
      - ./poetry.lock:/app/poetry.lock
      - ./.env:/app/.env
