services:
  my-service:
    image: kur0bot  # Replace with your Docker image name
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
  map-files:
    image: kur0bot  # Replace with your Docker image name
    volumes:
      - ./modules:/app/modules
      - ./myfunctions:/app/myfunctions
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
