"""
This type stub file was generated by pyright.
"""

class TextLorem:
    def __init__(self, wsep=..., ssep=..., psep=..., srange=..., prange=..., trange=..., words=...) -> None:
        ...
    
    def sentence(self) -> str: # -> str:
        ...
    
    def paragraph(self): # -> str:
        ...
    
    def text(self): # -> str:
        ...
    


